import { Trash2, MoreHorizontal, X, Box, Play, ChevronDown } from 'lucide-react'
import { useEffect } from 'react'
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
} from '../ui/dropdown-menu'
import { Button } from '../ui/button'

type Step = {
  id: string
  title: string
  content: string
  model?: string
  modelName?: string
  animation?: string
}

interface StepConfigurationProps {
  steps?: Step[]
  selectedIndex?: number | null
  onSelect?: (index: number) => void
  onUpdate?: (index: number, patch: Partial<Step>) => void
  onUnassign?: (index: number) => void
  onRemove?: (index: number) => void
  isSaving?: boolean
  assets?: Array<{ id: string; name?: string; originalFilename?: string; metadata?: any }>
}

export default function StepConfiguration({ steps = [], selectedIndex = null, onSelect, onUpdate, onUnassign, onRemove, isSaving = false, assets = [] }: StepConfigurationProps) {
  const selectedStep = selectedIndex === null ? null : steps[selectedIndex]

  // Ensure that when a model with animations is assigned, a default animation
  // is selected if none exists yet. Do this as an effect to avoid side-effects
  // during render.
  useEffect(() => {
    if (!onUpdate) return
    if (!steps || steps.length === 0) return
    if (!assets || assets.length === 0) return

    steps.forEach((step, idx) => {
      if (!step) return
      if (!step.model) return
      const asset = assets.find((a) => a.id === step.model)
      const animations = asset?.metadata?.animations || []
      if (animations.length > 0 && !step.animation) {
        // pick first animation by default
        onUpdate(idx, { animation: animations[0].name || '' })
      }
    })
  }, [steps, assets, onUpdate])

  return (
    <div className="mb-6">
      <div className="mt-4">
        {steps.length === 0 ? (
          <div className="p-6 bg-card text-card-foreground rounded-lg border border-dashed text-center text-muted-foreground">No steps yet. Click "Add Step" to begin.</div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 gap-3">
            {steps.map((step, idx) => (
              <div
                key={step.id}
                className={`bg-card text-card-foreground rounded-lg p-4 border ${selectedIndex === idx ? 'ring-1 ring-ring shadow-sm border-border' : 'border-border'} hover:shadow-md transition-shadow cursor-pointer`}
                onClick={(e) => {
                  const target = e.target as HTMLElement | null
                  // If the click originated from an interactive control (input, textarea, button, select, a),
                  // don't treat it as a card-select click so typing/focus works naturally.
                  if (target && target.closest('input, textarea, button, select, a')) return
                  onSelect && onSelect(idx)
                }}
              >
                <div className="flex gap-4">

                  <div className="flex-1">
                    <div className="flex items-center justify-between">
                      <div className="text-sm font-semibold text-foreground">{(() => {
                        const t = step.title && step.title.trim() ? step.title.trim() : ''
                        // treat titles that match the auto-generated pattern "Step <number>" as autogenerated
                        const isAuto = /^Step\s+\d+$/i.test(t)
                        return t && !isAuto ? t : `Step ${idx + 1}`
                      })()}</div>

                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button
                            onClick={(e) => e.stopPropagation()}
                            variant="ghost"
                            size="icon-sm"
                            title="More"
                          >
                            <MoreHorizontal className="w-4 h-4" />
                          </Button>
                        </DropdownMenuTrigger>

                        <DropdownMenuContent sideOffset={6} align="end">
                          <DropdownMenuItem onSelect={() => onRemove && onRemove(idx)}>
                            <Trash2 className="w-4 h-4 text-muted-foreground" />
                            <span>Delete</span>
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </div>

                    <textarea
                      value={step.content}
                      onChange={(e) => onUpdate && onUpdate(idx, { content: e.target.value })}
                      onClick={(e) => e.stopPropagation()}
                      onMouseDown={(e) => e.stopPropagation()}
                      placeholder="type step content here..."
                      disabled={isSaving}
                      className="w-full p-3 mt-2 border rounded-md bg-transparent text-foreground placeholder:text-muted-foreground min-h-[160px] resize-none text-xs disabled:opacity-50"
                    />

                    <div className="mt-3 flex items-start text-sm text-muted-foreground">
                      <div className="flex-shrink-0 w-full h-10 bg-muted rounded-md overflow-hidden flex items-center justify-between text-xs text-muted-foreground px-2">
                        {step.model ? (
                          <div className="flex items-center gap-4 w-full">
                            <div className="flex items-center justify-center w-8 h-8 bg-muted rounded-md">
                              <Box className="w-4 h-4 text-muted-foreground" />
                            </div>

                            <div className="text-left ml-0.5">
                              <div className="font-semibold text-foreground">{(step as any).modelName ?? step.model}</div>
                            </div>

                            <div className="ml-auto">
                              <Button
                                onClick={(e) => {
                                  e.stopPropagation()
                                  if (onUnassign) return onUnassign(idx)
                                  onUpdate && onUpdate(idx, { model: undefined })
                                }}
                                variant="ghost"
                                size="icon-sm"
                                title="Unassign model"
                              >
                                <X className="w-4 h-4" />
                              </Button>
                            </div>
                          </div>
                        ) : (
                          <div className="flex items-center gap-0 w-full">
                            <div className="flex items-center justify-center w-8 h-8 bg-muted rounded-md">
                              <Box className="w-4 h-4 text-muted-foreground" />
                            </div>

                            <div className="text-left">
                              <div className="font-medium text-foreground">3D Model</div>
                            </div>
                          </div>
                        )}
                      </div>
                    </div>

                    {/* Animation slot (mirrors the 3D model slot styling) */}
                    <div className="mt-3 flex items-start text-sm text-muted-foreground">
                      <div className="flex-shrink-0 w-full h-10 bg-muted rounded-md overflow-hidden flex items-center justify-between text-xs text-muted-foreground px-2">
                        {step.model ? (
                          (() => {
                            const asset = (assets || []).find((a) => a.id === step.model)
                            const animations = asset?.metadata?.animations || []
                            return (
                              <div className="flex items-center gap-3 w-full">
                                <div className="flex items-center justify-center w-8 h-8 bg-muted rounded-md">
                                  <Play className="w-4 h-4 text-muted-foreground" />
                                </div>

                                <div className="text-left w-full">
                                  {animations.length === 0 ? (
                                    <div className="pl-2 text-xs text-muted-foreground">no animtion</div>
                                  ) : (
                                    <DropdownMenu>
                                      <DropdownMenuTrigger asChild>
                                        <Button onClick={(e) => e.stopPropagation()} variant="ghost" size="sm" className="w-full justify-between px-2 hover:bg-accent/5">
                                          <div className="flex items-center">
                                            <span className="text-xs text-left">{(step as any).animation || '(none)'}</span>
                                          </div>
                                          <ChevronDown className="w-4 h-4 text-muted-foreground" />
                                        </Button>
                                      </DropdownMenuTrigger>

                                      <DropdownMenuContent sideOffset={6} align="start">
                                        <DropdownMenuItem onSelect={() => { onUpdate && onUpdate(idx, { animation: '' }) }}>
                                          (none)
                                        </DropdownMenuItem>
                                        {animations.map((a: any, i: number) => (
                                          <DropdownMenuItem key={i} onSelect={() => { onUpdate && onUpdate(idx, { animation: a.name }) }}>
                                            {a.name || `clip-${i}`}
                                          </DropdownMenuItem>
                                        ))}
                                      </DropdownMenuContent>
                                    </DropdownMenu>
                                  )}
                                </div>
                              </div>
                            )
                          })()
                        ) : (
                          <div className="flex items-center gap-0 w-full">
                            <div className="flex items-center justify-center w-8 h-8 bg-muted rounded-md">
                              <Box className="w-4 h-4 text-muted-foreground" />
                            </div>

                            <div className="text-left">
                              <div className="font-medium text-foreground">Animation</div>
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
